vich_uploader:
    db_driver: orm

    mappings:
       products:
           uri_prefix: /assets/images/properties
           upload_destination: '%kernel.project_dir%/public/assets/images/properties'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           delete_on_update: true
           delete_on_remove: true
